name: 'Apply Patches'
description: 'Checkout flock into the path "flock" and then apply the patches'
inputs:
  flutter_ref:
    required: true
    description: "the ref of the flutter repo to use as a base"

  flutter_repo:
    required: false
    description: "the flutter repo to use as a base"
    default: jezell/flutter

  token: 
    required: false
    description: "access token"
    default: ${{ github.token }}

  email:
    required: false
    default: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
    description: "the committer email"

  user_name:
    required: false
    description: "the committer name"
    default: "${{ github.actor }}"

  fetch_depth:
    required: false
    default: 1

runs:
  using: "composite"
  steps:
    - name: Checkout Flutter
      uses: actions/checkout@v4
      with:
        path: 'flock'
        repository: ${{inputs.flutter_repo}}
        ref: '${{inputs.flutter_ref}}'
        token: ${{ inputs.token }}
    
    - name: Apply Nest patches to Flock
      shell: bash
      run: |
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "${{ inputs.user_name }}"
        tools/git-import-patches patches