on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

name: create-flock-pr-from-nest-patch
permissions:
  contents: write

jobs:
  send-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nest
        uses: actions/checkout@v4
        with:
          path: 'nest'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: 'join-the-flock/nest'
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Flock
        uses: actions/checkout@v4
        with:
          path: 'nest/flock'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: 'join-the-flock/flock'
          ref: 'master'
          token: ${{ secrets.REPO_WORKFLOW_PAT }}

      - name: Create branch for PR
        working-directory: nest/flock
        run: |
          git config --global user.email "nobody@getflocked.dev"
          git config --global user.name "PR Bot"
          git checkout -b pr_workflow_test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Apply Nest patches to Flock
        run: |
          cd nest
          tools/git-import-patches patches

      - name: Push Flock changes to Flock repo for PR
        working-directory: nest/flock
        run: |
          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "${{ secrets.REPO_WORKFLOW_PAT }}" > token.txt

          # git remote set-url origin https://${{ secrets.REPO_WORKFLOW_PAT }}@github.com/join-the-flock/flock

          git push origin pr_workflow_test

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt
          gh pr create \
            --body "This PR body came from the workflow file" \
            --title "This title came from the workflow file" \
            --head "pr_workflow_test" \
            --base "master"
