name: Label
on:
  label:
    types: [ created ]
jobs:
  apply-and-push-changes:
    name: Patch, Test, and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nest
        uses: actions/checkout@v4
        with:
          path: ''
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Apply Patches
        uses: ./.github/actions/apply-patches
        with:
          email: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          user_name: "${{ github.actor }}"
          fetch_depth: 0

      - name: Run Framework Tests
        uses: ./.github/actions/run-framework-tests
        with:
          flutter_path: flock

      - name: Push to destination
        run: |
          cd flock
          git remote add destination ${{ vars.DESTINATION_REPO }}
          git tag ${{ vars.FLOCK_REF_PREFIX }}${{ github.event.label.name }}
          git push -f destination ${{ vars.FLOCK_REF_PREFIX }}${{ github.event.label.name }}