name: Push
on:
  - push
jobs:
  apply-and-push-changes:
    name: Patch, Test, and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nest
        uses: actions/checkout@v4
        with:
          path: ''
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Apply Patches
        uses: ./.github/actions/apply-patches
        with:
          token: ${{ secrets.REPO_WORKFLOW_PAT || secrets.GITHUB_TOKEN }}
          flutter_ref: "${{ vars.FLUTTER_BASE_REF || github.base_ref || github.ref_name }}"
          email: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          user_name: "${{ github.actor }}"

      - name: Run Framework Tests
        uses: ./.github/actions/run-framework-tests
        with:
          flutter_path: flock

      - name: Push to destination
        run: |
          cd flock
          git remote add destination ${{ vars.DESTINATION_REPO }}
          git checkout -b flock-temp
          git push -f destination flock-temp:${{ vars.FLOCK_REF_PREFIX }}${{ github.base_ref || github.ref_name }}
